apiVersion: v1
kind: ConfigMap
metadata:
  name: http-config
data:
  VERSION: 1.1.2
  logLevel: "5"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: httpserver:1.0.5
          env:
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: http-config
                  key: VERSION
          # 延迟探测、探活
          startupProbe:
            httpGet:
              path: /healthz?from=start
              port: 8080
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz?from=ready
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz?from=live
              port: 8080
            periodSeconds: 10
            failureThreshold: 6
          lifecycle:
            postStart: 
              exec:
                command: ["/bin/sh","-c","echo '容器启动' $(date) >> /var/log/start.log && printenv >> /var/log/start.log"]
            preStop:
              exec:
                command: ["/bin/sh","-c","kill -SIGHUP 1"]
          # 资源限制 Qos
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: httpserver

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - cncamp.com
      secretName: cncamp-tls
  rules:
    - host: cncamp.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: http-service
                port:
                  number: 80